const { Client } = require("pg");

const sql = `
create table if not exists error_log (
  id bigint generated by default as identity primary key,
  source text not null,
  message text not null,
  detail jsonb,
  created_at timestamptz not null default now()
);

create index if not exists error_log_created_idx on error_log(created_at desc);

alter table error_log enable row level security;

drop policy if exists "error_log_insert" on error_log;
drop policy if exists "error_log_select" on error_log;
create policy "error_log_insert" on error_log for insert with check (true);
create policy "error_log_select" on error_log for select using (true);
`;

async function main() {
  const client = new Client({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false },
  });
  await client.connect();
  try {
    await client.query(sql);
    console.log("Migration 6 applied successfully.");
  } finally {
    await client.end();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
