const { Client } = require("pg");

const sql = `
create table if not exists join_requests (
  id bigint generated by default as identity primary key,
  room_name text not null references rooms(name) on delete cascade,
  identity text not null,
  display_name text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  unique (room_name, identity)
);

create index if not exists join_requests_room_status_idx on join_requests(room_name, status);

alter table join_requests enable row level security;

drop policy if exists "join_requests_select" on join_requests;
drop policy if exists "join_requests_insert" on join_requests;
drop policy if exists "join_requests_update" on join_requests;
create policy "join_requests_select" on join_requests for select using (true);
create policy "join_requests_insert" on join_requests for insert with check (true);
create policy "join_requests_update" on join_requests for update using (true);

alter publication supabase_realtime add table join_requests;
`;

async function main() {
  const client = new Client({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false },
  });
  await client.connect();
  try {
    await client.query(sql);
    console.log("Migration 2 applied successfully.");
  } finally {
    await client.end();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
