const { Client } = require("pg");

const sql = `
alter table rooms add column if not exists cohost_secrets text[] not null default '{}';

create table if not exists polls (
  id bigint generated by default as identity primary key,
  room_name text not null references rooms(name) on delete cascade,
  question text not null,
  options jsonb not null,
  created_by text not null,
  closed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists poll_votes (
  poll_id bigint not null references polls(id) on delete cascade,
  identity text not null,
  option_index int not null,
  created_at timestamptz not null default now(),
  primary key (poll_id, identity)
);

create index if not exists polls_room_idx on polls(room_name, created_at);

alter table polls enable row level security;
alter table poll_votes enable row level security;

drop policy if exists "polls_select" on polls;
drop policy if exists "polls_insert" on polls;
drop policy if exists "polls_update" on polls;
create policy "polls_select" on polls for select using (true);
create policy "polls_insert" on polls for insert with check (true);
create policy "polls_update" on polls for update using (true);

drop policy if exists "poll_votes_select" on poll_votes;
drop policy if exists "poll_votes_insert" on poll_votes;
create policy "poll_votes_select" on poll_votes for select using (true);
create policy "poll_votes_insert" on poll_votes for insert with check (true);

alter publication supabase_realtime add table polls;
alter publication supabase_realtime add table poll_votes;
`;

async function main() {
  const client = new Client({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false },
  });
  await client.connect();
  try {
    await client.query(sql);
    console.log("Migration 3 applied successfully.");
  } finally {
    await client.end();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
