const { Client } = require("pg");

const sql = `
create table if not exists rooms (
  name text primary key,
  host_secret text not null,
  locked boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  room_name text not null references rooms(name) on delete cascade,
  sender text not null,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists messages_room_idx on messages(room_name, created_at);

alter table rooms enable row level security;
alter table messages enable row level security;

drop policy if exists "rooms_select" on rooms;
drop policy if exists "rooms_insert" on rooms;
drop policy if exists "rooms_update" on rooms;
create policy "rooms_select" on rooms for select using (true);
create policy "rooms_insert" on rooms for insert with check (true);
create policy "rooms_update" on rooms for update using (true);

drop policy if exists "messages_select" on messages;
drop policy if exists "messages_insert" on messages;
create policy "messages_select" on messages for select using (true);
create policy "messages_insert" on messages for insert with check (true);

alter publication supabase_realtime add table messages;
`;

async function main() {
  const client = new Client({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false },
  });
  await client.connect();
  try {
    await client.query(sql);
    console.log("Migration applied successfully.");
  } finally {
    await client.end();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
